name: Generate VPM repository

on:
  pull_request:

permissions:
  contents: write

env:
  vpm_repo_author: VirtualAviationJapan
  vpm_repo_id: jp.virtualaviation
  vpm_repo_name: VirtualAviationJapan
  vpm_repo_url: https://virtualaviationjapan.github.io/vpm/vpm.json

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.head_ref }}
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: >
          uv run main.py
          ${{ env.vpm_repo_author}}
          ${{ env.vpm_repo_id }}
          ${{ env.vpm_repo_name }}
          ${{ env.vpm_repo_url}}
          vpm.json
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore: update vpm.json"
